name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++ # Add any additional dependencies

    # Build the project
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Run tests (if applicable)
    - name: Run Tests
      run: |
        cd build
        ctest # Adjust based on your testing framework